gnome-terminal -- python3 main.py 0 0 0 
gnome-terminal -- python3 main.py 0 0 1
gnome-terminal -- python3 main.py 0 0 2
gnome-terminal -- python3 main.py 0 0 3
gnome-terminal -- python3 main.py 0 0 4
gnome-terminal -- python3 main.py 0 0 5
gnome-terminal -- python3 main.py 0 1 0
gnome-terminal -- python3 main.py 0 1 1
gnome-terminal -- python3 main.py 0 1 2
gnome-terminal -- python3 main.py 0 1 3
gnome-terminal -- python3 main.py 0 1 4
gnome-terminal -- python3 main.py 0 1 5
gnome-terminal -- python3 main.py 0 2 0
gnome-terminal -- python3 main.py 0 2 1
gnome-terminal -- python3 main.py 0 2 2
gnome-terminal -- python3 main.py 0 2 3
gnome-terminal -- python3 main.py 0 2 4
gnome-terminal -- python3 main.py 0 2 5
gnome-terminal -- python3 main.py 1 0 0 
gnome-terminal -- python3 main.py 1 0 1 
gnome-terminal -- python3 main.py 1 0 2 
gnome-terminal -- python3 main.py 1 0 3 
gnome-terminal -- python3 main.py 1 0 4 
gnome-terminal -- python3 main.py 1 0 5 
gnome-terminal -- python3 main.py 1 1 0 
gnome-terminal -- python3 main.py 1 1 1 
gnome-terminal -- python3 main.py 1 1 2 
gnome-terminal -- python3 main.py 1 1 3 
gnome-terminal -- python3 main.py 1 1 4 
gnome-terminal -- python3 main.py 1 1 5 
gnome-terminal -- python3 main.py 1 2 0 
gnome-terminal -- python3 main.py 1 2 1 
gnome-terminal -- python3 main.py 1 2 2 
gnome-terminal -- python3 main.py 1 2 3 
gnome-terminal -- python3 main.py 1 2 4 
gnome-terminal -- python3 main.py 1 2 5 
gnome-terminal -- python3 main.py 2 0 0 
gnome-terminal -- python3 main.py 2 0 1 
gnome-terminal -- python3 main.py 2 0 2 
gnome-terminal -- python3 main.py 2 0 3 
gnome-terminal -- python3 main.py 2 0 4 
gnome-terminal -- python3 main.py 2 0 5 
gnome-terminal -- python3 main.py 2 1 0 
gnome-terminal -- python3 main.py 2 1 1 
gnome-terminal -- python3 main.py 2 1 2 
gnome-terminal -- python3 main.py 2 1 3 
gnome-terminal -- python3 main.py 2 1 4 
gnome-terminal -- python3 main.py 2 1 5 
gnome-terminal -- python3 main.py 2 2 0 
gnome-terminal -- python3 main.py 2 2 1 
gnome-terminal -- python3 main.py 2 2 2 
gnome-terminal -- python3 main.py 2 2 3 
gnome-terminal -- python3 main.py 2 2 4 
gnome-terminal -- python3 main.py 2 2 5 

